### PR TITLE
Store music in ~/Music/gmplayer/<artist>/<album>/<track>

### LINKED ISSUE #3: Store tracks in folders per album/artist
Currently, all tracks are stored in the root level music directory.

This will quickly become messy, especially with the introduction of album/playlist support.

I think we should create a directory in the music root with a name of `gmplayer`, and then store all downloaded tracks in there in the format of `~/Music/gmplayer/<artist>/<album>/<tracknumber> - <title>.mp3`.

Note: I plan on implementing this, but I figured I would make an issue first to see what you think :smile:

### LINKED ISSUE #4: Handle songs with slashes in the track title
Currently, trying to play a song that contains a `/` in the name will crash gmplayer.

Steps to reproduce:

```
 λ ./gmplayer -s The Beyond flying lotus
Looking up requested song -
[0] Your Potential//The Beyond (feat. Niki Randa) - Flying Lotus
What song do you want to play? #0

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/nickj/Music/Your Potential/The Beyond (feat. Niki Randa) - Flying Lotus.mp3'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at IncomingMessage.<anonymous> (/Users/nickj/Projects/gmplayer/app.js:203:14)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at IncomingMessage.Readable.push (_stream_readable.js:110:10)
    at HTTPParser.parserOnBody (_http_common.js:109:22)
    at TLSSocket.socketOnData (_http_client.js:305:20)
```

We should probably sanitize the filename before saving. Maybe https://www.npmjs.com/package/sanitize-filename? (seems like it might be overkill)

### PR DESCRIPTION
**Pull request by Widdershin**
Also sanitize filenames. Closes #3 and closes #4

### CODE REVIEW

**Comment by 96AA48** [comment]
Nice work, I took a look at the implementation for the artist/album sorting and it looks good. Good way of implenting `album.artist` vs `song.artist`. Merging later today after testing.

**Comment by 96AA48** [comment]
I tried it out on several albums. Dr.Dre's Compton just seems to [skip all of the songs except for the first and last](http://i.imgur.com/ULFQRE2.png) for some reason. Also Whizz Khalifa and Snoop Dogg's "Mac and Devin Go To Highschool" won't play at all. [The cause seems to be a that the `album.artist` implementation isn't working](http://i.imgur.com/eBkZBzX.png), it's causing multiple directories to spawn if there isn't a indiviual artist in the album. I think a naming scheme like so `~/Music/gmplayer/<album>/<songname> - <artist>.mp3` would be better.

**Comment by Widdershin** [comment]
>  I think a naming scheme like so `~/Music/gmplayer/<album>/<songname> - <artist>.mp3` would be better.

That would definitely solve the problem you've pointed. The only issue I can see with that is if there are multiple albums by different artists that share the same name, they'll show up in the same folder. This will only be a minor (mostly cosmetic issue) as the `.m3u` files will still point at the right songs.

I admit I'm a little attached to artist folders, as I like that they provide an easy way of navigating libraries (they group albums by an artist).

I have another potential solution. If we detect that an album has multiple artists, place it in `~/Music/gmplayer/Various Artists/<songname>.mp3`

(Note: I also don't mind using other formats for the track filename along with this proposal, like `<songname> - <artist>.mp3`, if that's something you have a strong affinity for)

**Comment by 96AA48** [comment]
We could also implement this as a small config option to sort by a defined string that the user sets. Literally just by supplying strings like `<songname> - <artist>.mp3` or `gmplayer/<album>/<songname> - <artist>.mp3` to maximize customization. We could go for the "Various artists" implementation for the default method of sorting or something along those lines.

**Comment by Digikid13** [comment]
I would like to see a param in ```~/.gmplayerrc``` that looks something like this:
```savLoc: '~/Music/{genre}/{albumnArtist}'```

With that we can just parse that value and generate a save location, so the user has more control over it.

Relevent Params:
```
{
    title,
    artist,
    composer,
    album,
    albumArtist,
    year,
    trackNumber,
    genre
}
```

**Comment by 96AA48** [comment]
I'm trying to implement the feature that @Digikid13 proposed. I have to say tho, your implementation of the playlists are sounding pretty good @Widdershin, good job!

**Comment by 96AA48** [comment]
I fixed the issue with the multiple folders per artist on the `[Widdershin-folders](https://github.com/96AA48/gmplayer/compare/Widdershin-folders)` branch. I also implemented the customisation system that we talked about. The implementation basically allows the use of any of the data that is supplied with the track object. This way we can all basically have our own way of storing the music in the way we want it. We can still talk about the default values for this implementation however. If you guys are gonna run this, don't forget to clear your ~/.gmplayerrc.

**Comment by Widdershin** [comment]
I've pulled in your changes, really nice!

This is the config I'm using:

```
{
  "tracknaming": "{title}",
  "albumnaming": "{artist}/{album}",
  "playlistnaming": "{name} - {artist}"
}
```

Check out the extra couple of commits I made.

**Comment by Widdershin** [comment]
Okay, so this config and 461399d addresses the problem we were talking about above (ie: Dr Dre's Compton).
```
{
  "tracknaming": "{title}",
  "albumnaming": "{albumArtist}/{album}",
  "playlistnaming": "{name} - {albumArtist}"
}
```
Four of the songs on that album don't have the album artist set to "Dr. Dre". The rest do. So now we force all tracks (downloaded as part of an album) to have the albumArtist of the album they came from.

This does mean that using single songs with strange album artists with the above configuration will still make lots of folders, but it's definitely an improvement.

**Comment by 96AA48** [comment]
Pulled in your changes as well, nice little additions/fixes. Totally overlooked the sanitation of the entire `customName` string, my bad. Thanks for the help. I have run into a bug but that's unrelated to this pull request/ issue. We'll merge it!

**Pull request merged**
